In [2]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in c:\users\lokes\appdata\local\programs\python\python312\lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in c:\users\lokes\appdata\local\programs\python\python312\lib\site-packages (from ucimlrepo) (2.3.1)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\lokes\appdata\local\programs\python\python312\lib\site-packages (from ucimlrepo) (2025.8.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lokes\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lokes\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lokes\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lokes\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lokes\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
from ucimlrepo import fetch_ucirepo

In [4]:
statlog_heart = fetch_ucirepo(id=145)

In [5]:
x = statlog_heart.data.features 
y = statlog_heart.data.targets

In [6]:
x

,age,sex,chest-pain,rest-bp,serum-chol,fasting-blood-sugar,electrocardiographic,max-heart-rate,angina,oldpeak,slope,major-vessels,thal
0,70.0,1.0,4.0,130.0,322.0,0.0,2.0,109.0,0.0,2.4,2.0,3.0,3.0
1,67.0,0.0,3.0,115.0,564.0,0.0,2.0,160.0,0.0,1.6,2.0,0.0,7.0
2,57.0,1.0,2.0,124.0,261.0,0.0,0.0,141.0,0.0,0.3,1.0,0.0,7.0
3,64.0,1.0,4.0,128.0,263.0,0.0,0.0,105.0,1.0,0.2,2.0,1.0,7.0
4,74.0,0.0,2.0,120.0,269.0,0.0,2.0,121.0,1.0,0.2,1.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52.0,1.0,3.0,172.0,199.0,1.0,0.0,162.0,0.0,0.5,1.0,0.0,7.0
266,44.0,1.0,2.0,120.0,263.0,0.0,0.0,173.0,0.0,0.0,1.0,0.0,7.0
267,56.0,0.0,2.0,140.0,294.0,0.0,2.0,153.0,0.0,1.3,2.0,0.0,3.0
268,57.0,1.0,4.0,140.0,192.0,0.0,0.0,148.0,0.0,0.4,2.0,0.0,6.0
269,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0

In [7]:
y

     heart-disease
0                2
1                1
2                2
3                1
4                1
..             ...
265              1
266              1
267              1
268              1
269              2

[270 rows x 1 columns]

In [8]:
df = x

In [9]:
df['target']=y

In [10]:
df.head()

,age,sex,chest-pain,rest-bp,serum-chol,fasting-blood-sugar,electrocardiographic,max-heart-rate,angina,oldpeak,slope,major-vessels,thal,target
0,70.0,1.0,4.0,130.0,322.0,0.0,2.0,109.0,0.0,2.4,2.0,3.0,3.0,2
1,67.0,0.0,3.0,115.0,564.0,0.0,2.0,160.0,0.0,1.6,2.0,0.0,7.0,1
2,57.0,1.0,2.0,124.0,261.0,0.0,0.0,141.0,0.0,0.3,1.0,0.0,7.0,2
3,64.0,1.0,4.0,128.0,263.0,0.0,0.0,105.0,1.0,0.2,2.0,1.0,7.0,1
4,74.0,0.0,2.0,120.0,269.0,0.0,2.0,121.0,1.0,0.2,1.0,1.0,3.0,1

In [11]:
df.isnull().sum()

age                     0
sex                     0
chest-pain              0
rest-bp                 0
serum-chol              0
fasting-blood-sugar     0
electrocardiographic    0
max-heart-rate          0
angina                  0
oldpeak                 0
slope                   0
major-vessels           0
thal                    0
target                  0
dtype: int64

In [12]:
from sklearn.model_selection import train_test_split 
X_train ,X_test,y_train,y_test = train_test_split(df.drop(['target'],axis='columns'),df['target'],test_size=0.3,random_state=42)

In [13]:
len(X_train)

189

In [14]:
len(X_test)

81

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
lr = LogisticRegression()

In [17]:
lr.fit(X_train,y_train)

C:\Users\lokes\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [18]:
lr.score(X_test,y_test)

0.8641975308641975

In [19]:
y_pred_lr = lr.predict(X_test)

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_lr))

              precision    recall  f1-score   support

           1       0.85      0.94      0.89        49
           2       0.89      0.75      0.81        32

    accuracy                           0.86        81
   macro avg       0.87      0.84      0.85        81
weighted avg       0.87      0.86      0.86        81

In [22]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200,
    max_depth=10,
    min_samples_split=5,
    random_state=42)

In [23]:
rf.fit(X_train,y_train)

RandomForestClassifier(max_depth=10, min_samples_split=5, n_estimators=200,
                       random_state=42)

In [24]:
rf.score(X_test,y_test)

0.8518518518518519

In [25]:
y_pred_rf = rf.predict(X_test)

In [26]:
print(classification_report(y_test,y_pred_rf))

              precision    recall  f1-score   support

           1       0.82      0.96      0.89        49
           2       0.92      0.69      0.79        32

    accuracy                           0.85        81
   macro avg       0.87      0.82      0.84        81
weighted avg       0.86      0.85      0.85        81

In [46]:
from sklearn.svm import SVC
svc = SVC(C=13.0,gamma='scale')

In [47]:
svc.fit(X_train,y_train)

SVC(C=13.0)

In [48]:
svc.score(X_test,y_test)

0.654320987654321

In [49]:
y_pred_svc = svc.predict(X_test)

In [50]:
print(classification_report(y_test,y_pred_svc))

              precision    recall  f1-score   support

           1       0.70      0.76      0.73        49
           2       0.57      0.50      0.53        32

    accuracy                           0.65        81
   macro avg       0.63      0.63      0.63        81
weighted avg       0.65      0.65      0.65        81